<script setup lang="ts">
import { ChevronDown, Inbox, Paperclip } from '@lucide/vue'
import { formatDateTime } from '~/lib/access-it/time'

// Every email the module would have sent, newest first. Mocked until the mail service is connected.
const { sentEmails } = useSiteAttendance()

const expandedIds = ref(new Set<number>())

const sorted = computed(() => [...sentEmails.value].sort((left, right) => right.sentAt.localeCompare(left.sentAt)))

function toggle(id: number) {
  const next = new Set(expandedIds.value)
  if (next.has(id)) next.delete(id)
  else next.add(id)
  expandedIds.value = next
}
</script>

<template>
  <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
    <header class="flex flex-col gap-2 border-b border-slate-100 bg-slate-50 px-5 py-4 sm:flex-row sm:items-center sm:justify-between">
      <div>
        <h2 class="text-base font-semibold text-ink">Sent emails</h2>
        <p class="mt-1 text-sm text-slate-500">Emails generated by the automations above. In this proof of concept they are recorded here rather than delivered.</p>
      </div>
      <p class="text-sm text-slate-500"><span class="font-semibold text-slate-700">{{ sorted.length }}</span> {{ sorted.length === 1 ? 'email' : 'emails' }}</p>
    </header>

    <ul v-if="sorted.length" class="divide-y divide-slate-100">
      <li v-for="email in sorted" :key="email.id">
        <button type="button" class="flex w-full items-start justify-between gap-4 px-5 py-4 text-left outline-hidden transition hover:bg-soter-50/60 focus-visible:bg-soter-50/60" :aria-expanded="expandedIds.has(email.id)" @click="toggle(email.id)">
          <div class="flex min-w-0 gap-4">
            <span class="mt-0.5 shrink-0 rounded-md bg-soter-50 px-2 py-1 font-mono text-[11px] font-semibold text-soter-700">{{ email.runOrder }}</span>
            <div class="min-w-0">
              <p class="font-medium text-ink">{{ email.subject }}</p>
              <p class="mt-0.5 truncate text-sm text-slate-500">To {{ email.to }}</p>
            </div>
          </div>
          <div class="flex shrink-0 items-center gap-3 text-xs text-slate-500">
            <span class="whitespace-nowrap">{{ formatDateTime(email.sentAt) }}</span>
            <ChevronDown class="size-4 transition" :class="expandedIds.has(email.id) ? 'rotate-180' : ''" />
          </div>
        </button>
        <div v-if="expandedIds.has(email.id)" class="border-t border-slate-100 bg-slate-50 px-5 py-4">
          <pre class="whitespace-pre-wrap font-sans text-sm leading-6 text-slate-700">{{ email.body }}</pre>
          <p v-if="email.attachment" class="mt-3 inline-flex items-center gap-1.5 text-xs text-slate-500"><Paperclip class="size-3.5" /> {{ email.attachment }}</p>
        </div>
      </li>
    </ul>
    <div v-else class="flex flex-col items-center gap-2 px-5 py-14 text-center text-sm text-slate-500">
      <Inbox class="size-8 text-slate-300" />
      No emails have been sent yet. Log a visitor or contractor on to see automations fire.
    </div>
  </section>
</template>
